language: node_js
node_js:
- 10.9.0
brancher:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm install
addons:
  ssh_known_hosts:
  - 182.92.75.69
before_script: 
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_70e5cdf8cfb1_key -iv $encrypted_70e5cdf8cfb1_iv
  -in id_rsa_git.enc -out ~\/.ssh/id_rsa_git -d
